litellm_settings:
  drop_params: true

model_list:
  - model_name: "github_copilot/*"
    litellm_params:
      model: "github_copilot/*"
      extra_headers: {
        "editor-version": "vscode/1.104.1",
        "editor-plugin-version": "copilot/1.155.0",
        "Copilot-Integration-Id": "vscode-chat",
        "user-agent": "GithubCopilot/1.155.0"
      }

  # fallback
  - model_name: "*"
    litellm_params:
      model: "*"
